CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255) NULL,
	username VARCHAR(100) UNIQUE NOT NULL,
	email VARCHAR(255) NULL,
	avatar TEXT,
	exp TIMESTAMP NULL
)


CREATE TABLE sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_token VARCHAR(255) NOT NULL,
    user_id CHAR(24) NOT NULL,
    expires DATETIME NOT NULL
)


CREATE TABLE accounts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	access_token TEXT NOT NULL,
	scope TEXT NOT NULL,
	token_type VARCHAR(20) NOT NULL,
	providerAccountId VARCHAR(50) NOT NULL,
	provider VARCHAR(50) NOT NULL,
	type VARCHAR(20) NOT NULL,
	userId CHAR(24) NOT NULL,
)
